services:
  ftb-server:
    image: ghcr.io/weedz/ftb-server:latest
    ports:
      - "25565:25565"
    environment:
      MOD_ID: 101
      VERSION_ID: 2336
      EULA: 1
    restart: unless-stopped
    volumes:
     - ftb-server:/app
volumes:
  ftb-server:
